import os
import subprocess
from pathlib import Path
import markdown
from weasyprint import HTML
import yaml
import json
import re
import shutil

from src.exceptions import RenderError

def _json_to_rendercv_yaml(json_content: dict, personal_info: dict) -> dict:
    """
    Map JSON Resume object to RenderCV YAML dictionary.
    """
    basics = json_content.get("basics", {})
    name = basics.get("name", "John Doe")
    email = basics.get("email", "john@example.com")
    summary = basics.get("summary", "")

    sections = {}

    if summary:
        sections["Summary"] = [summary]

    skills = json_content.get("skills", [])
    if skills:
        sections["Skills"] = []
        for skill in skills:
            skill_name = skill.get("name", "")
            keywords = skill.get("keywords", [])
            if isinstance(keywords, list):
                keywords_str = ", ".join(keywords)
            else:
                keywords_str = str(keywords)
            sections["Skills"].append(f"**{skill_name}**: {keywords_str}")

    work = json_content.get("work", [])
    if work:
        sections["Experience"] = []
        for w in work:
            company = w.get("name", "")
            position = w.get("position", "")
            summary_w = w.get("summary", "")
            highlights = w.get("highlights", [])

            lines = []
            if company or position:
                lines.append(f"**{company}**, {position}")
            if summary_w:
                lines.append(summary_w)
            for h in highlights:
                lines.append(f"- {h}")
            sections["Experience"].append("\n".join(lines))

    education = json_content.get("education", [])
    if education:
        sections["Education"] = []
        for e in education:
            inst = e.get("institution", "")
            area = e.get("area", "")
            studyType = e.get("studyType", "")
            sections["Education"].append(f"**{inst}** - {studyType} in {area}")

    cv_data = {
        "name": name,
        "email": email,
        "sections": sections
    }

    design_data = {
        "theme": personal_info.get("theme", "classic")
    }

    return {"cv": cv_data, "design": design_data}

def render_resume_pdf(job, output_dir: Path, theme: str, user_dir: Path, engine: str = "rendercv") -> Path:
    """
    Verify `resume.json` exists (raise `RenderError` if not); call `_json_to_rendercv_yaml()`;
    write `resume.yaml`; invoke `rendercv render resume.yaml` via `subprocess`;
    verify output PDF exists; raise `RenderError` if not; return PDF path.
    Or, if engine is jsonresume, use resumed and weasyprint.
    """
    resume_json_path = output_dir / "resume.json"
    if not resume_json_path.exists():
        raise RenderError(f"Source JSON file missing: {resume_json_path}")

    if engine == "jsonresume":
        html_path = output_dir / "resume.html"
        pdf_path = output_dir / "resume.pdf"

        try:
            result = subprocess.run(
                ["npx", "-y", "resumed", "export", "--theme", "jsonresume-theme-class", "resume.json", "-o", "resume.html"],
                cwd=output_dir, capture_output=True, text=True
            )
            if result.returncode != 0:
                raise RenderError(f"resumed exited with code {result.returncode}: {result.stderr}")
        except Exception as e:
            if isinstance(e, RenderError):
                raise
            raise RenderError(f"Failed to run resumed: {e}")

        try:
            HTML(filename=str(html_path)).write_pdf(str(pdf_path))
        except Exception as e:
            raise RenderError(f"WeasyPrint failed: {e}")

        if not pdf_path.exists():
            raise RenderError("PDF was not generated by jsonresume engine.")

        return pdf_path

    # Default to rendercv engine
    with open(resume_json_path, 'r', encoding='utf-8') as f:
        try:
            json_content = json.load(f)
        except json.JSONDecodeError as e:
            raise RenderError(f"Failed to decode resume.json: {e}")

    personal_info = {"theme": theme}
    yaml_data = _json_to_rendercv_yaml(json_content, personal_info)

    resume_yaml_path = output_dir / "resume.yaml"
    with open(resume_yaml_path, 'w', encoding='utf-8') as f:
        yaml.dump(yaml_data, f)

    # Check for custom theme
    custom_theme_dir = user_dir / "templates" / theme
    if custom_theme_dir.exists() and custom_theme_dir.is_dir():
        target_theme_dir = output_dir / theme
        shutil.copytree(custom_theme_dir, target_theme_dir, dirs_exist_ok=True)

    try:
        result = subprocess.run(["rendercv", "render", "resume.yaml"], cwd=output_dir, capture_output=True, text=True)
        if result.returncode != 0:
            raise RenderError(f"RenderCV exited with code {result.returncode}: {result.stderr}")
    except Exception as e:
        if isinstance(e, RenderError):
            raise
        raise RenderError(f"Failed to run RenderCV: {e}")

    pdf_dir = output_dir / "rendercv_output"
    pdfs = list(pdf_dir.glob("*.pdf")) if pdf_dir.exists() else []

    if not pdfs:
        raise RenderError("RenderCV finished but no PDF was generated.")

    output_pdf = output_dir / "resume.pdf"
    os.replace(pdfs[0], output_pdf)
    return output_pdf

def render_cover_letter_pdf(job, output_dir: Path) -> Path:
    """
    Verify `cover_letter.md` exists (raise `RenderError` if not);
    convert markdown → HTML via `markdown` library;
    convert HTML → PDF via WeasyPrint; verify PDF written; return PDF path.
    """
    cl_md_path = output_dir / "cover_letter.md"
    if not cl_md_path.exists():
        raise RenderError(f"Source markdown file missing: {cl_md_path}")

    with open(cl_md_path, 'r', encoding='utf-8') as f:
        md_content = f.read()

    html_content = markdown.markdown(md_content)

    pdf_path = output_dir / "cover_letter.pdf"

    HTML(string=html_content).write_pdf(str(pdf_path))

    if not pdf_path.exists():
        raise RenderError("WeasyPrint finished but no PDF was generated.")

    return pdf_path
